name: Continuous Integration

on: [push, pull_request]

jobs:
  lint_and_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

#      - name: Lint
#        uses: golangci/golangci-lint-action@v2
#        with:
#          version: latest
#          only-new-issues: true

      - name: Test
        run: |-
          make test
